# Generated by Django 5.1 on 2025-11-06 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('suscriptores', models.IntegerField(default=0)),
                ('url_personalizada', models.CharField(max_length=100, unique=True)),
                ('pais', models.CharField(max_length=50)),
                ('categoria_principal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('duracion', models.DurationField()),
                ('vistas', models.IntegerField(default=0)),
                ('publico', models.BooleanField(default=True)),
                ('url_miniatura', models.CharField(max_length=200)),
                ('likes', models.CharField(max_length=200)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app_YouTube.canal')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('publica', models.BooleanField(default=True)),
                ('orden_videos', models.JSONField()),
                ('n_videos', models.DecimalField(decimal_places=0, max_digits=10)),
                ('canal_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='app_YouTube.canal')),
                ('videos', models.ManyToManyField(related_name='playlists', to='app_YouTube.video')),
            ],
        ),
    ]
