# Generated by Django 5.1 on 2025-11-18 19:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_YouTube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('pais', models.CharField(blank=True, max_length=50)),
                ('biografia', models.TextField(blank=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('es_verificado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='playlist',
            name='n_videos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_suscripcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('notificaciones_activadas', models.BooleanField(default=True)),
                ('nivel_suscripcion', models.CharField(choices=[('Gratis', 'Gratis'), ('Premium', 'Premium'), ('VIP', 'VIP')], default='Gratis', max_length=50)),
                ('comentarios_habilitados', models.BooleanField(default=True)),
                ('puntos_fidelidad', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='app_YouTube.canal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='app_YouTube.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('editado', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('respuesta_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='app_YouTube.comentario')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app_YouTube.video')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app_YouTube.usuario')),
            ],
        ),
    ]
